"""empty message

Revision ID: 432fceb10a2b
Revises: 4e24c4b0cc4c
Create Date: 2025-04-17 14:32:47.228521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432fceb10a2b'
down_revision = '4e24c4b0cc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
