"""messages

Revision ID: 4e24c4b0cc4c
Revises: b4632ef9b00b
Create Date: 2025-03-25 20:29:33.688478

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e24c4b0cc4c"
down_revision = "b4632ef9b00b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_seen", sa.DateTime(), nullable=True))

    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.drop_column("last_seen")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_seen", sa.DATETIME(), nullable=True))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_seen")

    # ### end Alembic commands ###
