"""Создание бд для профиля

Revision ID: 5e0500df559b
Revises: 96e1337ff171
Create Date: 2025-03-22 12:11:58.002032

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e0500df559b"
down_revision = "96e1337ff171"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("position", sa.String(length=200), nullable=True),
        sa.Column("profile_photo", sa.String(length=200), nullable=True),
        sa.Column("github_link", sa.String(length=100), nullable=True),
        sa.Column("telegram_link", sa.String(length=100), nullable=True),
        sa.Column("vk_link", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profile")
    # ### end Alembic commands ###
