"""pisya

Revision ID: 942df4d86980
Revises: f3bbd95fa4a9
Create Date: 2025-03-22 14:29:24.851997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942df4d86980'
down_revision = 'f3bbd95fa4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
