"""messages

Revision ID: b4632ef9b00b
Revises: 5999005b2fd3
Create Date: 2025-03-25 20:18:07.507918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4632ef9b00b'
down_revision = '5999005b2fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.drop_index('ix_message_timestamp')
        batch_op.drop_column('content')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.create_index('ix_message_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('text')

    # ### end Alembic commands ###
